apiVersion: v2
name: ckan-chart
description: A Helm chart for CKAN

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 2.8.5

# Dependencies
dependencies:
  - name: redis 
    version: 10.5.6
    repository: "https://kubernetes-charts.storage.googleapis.com/"
    condition: redis.enabled
  - name: solr
    version: 1.4.0
    repository: "https://charts.helm.sh/incubator"
    condition: solr.enabled
  - name: postgresql
    version: "10.1.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: datapusher
    version: "1.0.0"
    repository: "file://dependency-charts/datapusher"
    condition: datapusher.enabled

