name: Upload Helm chart to GCS bucket
on:
  create:
jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name:  Helm Chart to GCP bucket
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Package the helm chart
      run: |
        mkdir charts
        helm dep up
        helm package . --version "${{  github.ref_name }}" --destination charts
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}"
    - name: Upload the file
      run: |
        gcloud auth activate-service-account githubaction@keitaro-kubernetes-001.iam.gserviceaccount.com --key-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud config get-value account
        PACKED_CHART_NAME=$(basename -s charts/*.tgz)
        echo "Preparing to push ${PACKED_CHART_NAME} to keitaro-charts"
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        cd charts
        gsutil cp ${PACKED_CHART_NAME} gs://keitaro-charts
        gsutil cp gs://keitaro-charts/index.yaml .
        helm repo index . --merge index.yaml
        gsutil cp index.yaml gs://keitaro-charts
